[tool.ruff]
target-version = "py310"
line-length = 125

[tool.ruff.lint]
exclude = ["docs/extensions/*.py", "logs"]
select = [
    "A",
    "C4",
    "F",
    "G",
    "I",
    "PTH",
    "RUF",
    "SIM",
    "TC",
    "UP",
    "W",
    "PERF",
    "ANN",
]
ignore = [
    "F401",
    "F402",
    "F403",
    "F405",
    "PERF203",
    "RUF001",
    "RUF009",
    "SIM105",
    "UP034",
    "UP038",
    "UP007",
    "ANN401",
    "RUF052", # for filtering "local dummy variable is accessed" eg. - vars using `_`
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
combine-as-imports = true

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
parametrize-names-type = "tuple"

[tool.pyright]
useLibraryCodeForTypes = true
typeCheckingMode = "standard"
pythonVersion = "3.12"
reportIncompatibleMethodOverride = false
exclude = ["logs/**", "**/.venv/**"]
